/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import dao.ClienteDaoImpl;
import dao.ProdutoDaoImpl;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Produto;

/**
 *
 * @author bruno_busarello
 */
public class CadPedido extends javax.swing.JInternalFrame {
    ClienteDaoImpl clienteDaoImpl = new ClienteDaoImpl();
    ProdutoDaoImpl produtoDaoImpl = new ProdutoDaoImpl();
    /**
     * Creates new form CadPedido
     */
    public CadPedido() {
        initComponents();
        loadClients();
        loadProdutos();
    }

    public void loadClients(){
        List<Cliente> clientes = clienteDaoImpl.getAllClientes();
        for (Cliente cliente : clientes) {
            jCbCli.addItem(cliente.getNome());
        }
    }
    
    public void loadProdutos(){
        DefaultTableModel defaultPro = new DefaultTableModel(new Object[]{
            "Nome",
            "Preço"
        }, 0);
        
        
        List<Produto> produtos = produtoDaoImpl.getAllProdutos();
        for (Produto produto : produtos) {
            Object linha[] = new Object[] {
                produto.getDesc(),
                produto.getPreco(),
            };
            defaultPro.addRow(linha);
        }
        jTbPro.setModel(defaultPro);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCbCli = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbPro = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jCbCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbCliActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecione o cliente solicitante");

        jTbPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Preço"
            }
        ));
        jScrollPane1.setViewportView(jTbPro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCbCli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(jCbCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCbCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbCliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCbCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbPro;
    // End of variables declaration//GEN-END:variables
}
