/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import dao.ClienteDaoImpl;
import dao.PedidoDaoImpl;
import dao.ProdutoDaoImpl;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.InfPedido;
import model.Pedido;
import model.Produto;

/**
 *
 * @author bruno_busarello
 */
public class CadPedido extends javax.swing.JInternalFrame {
    private int count = 1;
    private int selected;
    private float maxCount = 0;
    ClienteDaoImpl clienteDaoImpl = new ClienteDaoImpl();
    ProdutoDaoImpl produtoDaoImpl = new ProdutoDaoImpl();
    PedidoDaoImpl pedidoDaoImpl = new PedidoDaoImpl();
    List<InfPedido> pedidos = new ArrayList<>();
    List<Integer> idClientes = new ArrayList<>();
    private int idCliente;
    /**
     * Creates new form CadPedido
     */
    public CadPedido() {
        initComponents();
        loadClients();
        loadProdutos();
    }

    public void loadClients(){
        List<Cliente> clientes = clienteDaoImpl.getAllClientes();
        for (Cliente cliente : clientes) {
            jCbCli.addItem(cliente.getNome());
            idClientes.add(cliente.getCodigo());
        }
    }
    
    public void loadProSelected(){
        DefaultTableModel defaultPro = new DefaultTableModel(new Object[]{
            "ID",
            "Quantidade"
        }, 0);
        
        for (int i = 0; i < pedidos.size(); i++) {
            Object linha[] = new Object[] {
                pedidos.get(i).getIdProduto(),
                pedidos.get(i).getQtd()
            };
            defaultPro.addRow(linha);
        }
        jTable1.setModel(defaultPro);
    }
    
    public void loadProdutos(){
        DefaultTableModel defaultPro = new DefaultTableModel(new Object[]{
            "Código",
            "Nome",
            "Preço",
            "Quantidade"
        }, 0);
        
        
        List<Produto> produtos = produtoDaoImpl.getAllProdutos();
        for (Produto produto : produtos) {
            Object linha[] = new Object[] {
                produto.getCod(),
                produto.getDesc(),
                produto.getPreco(),
                produto.getQtd()
            };
            defaultPro.addRow(linha);
        }
        jTbPro.setModel(defaultPro);
    }
    
    public int getIdCli(int index){
        return idClientes.get(index);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCbCli = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbPro = new javax.swing.JTable();
        btnSavePro = new javax.swing.JButton();
        btnAddPro = new javax.swing.JButton();
        btnMenosPro = new javax.swing.JButton();
        jLblQtd = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTfCod = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        jLbCodPro = new javax.swing.JTextField();
        jLbDescPro = new javax.swing.JTextField();
        LblMaxNumber = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jCbCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbCliActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecione o cliente solicitante");

        jTbPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Preço"
            }
        ));
        jTbPro.setEnabled(false);
        jTbPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbProMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTbPro);

        btnSavePro.setText("Adicionar");
        btnSavePro.setEnabled(false);
        btnSavePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveProActionPerformed(evt);
            }
        });

        btnAddPro.setText("+");
        btnAddPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProActionPerformed(evt);
            }
        });

        btnMenosPro.setText("-");
        btnMenosPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosProActionPerformed(evt);
            }
        });

        jLblQtd.setText("1");
        jLblQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLblQtdKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Qtd"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        btnSave.setText("Salvar Pedido");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel2.setText("ID pedido");

        jTfCod.setEnabled(false);

        btnNew.setText("Novo pedido");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        jLbCodPro.setEditable(false);

        jLbDescPro.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(9, 9, 9)
                        .addComponent(btnNew))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTfCod, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCbCli, javax.swing.GroupLayout.Alignment.LEADING, 0, 331, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLbCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLbDescPro, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddPro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMenosPro))
                            .addComponent(btnSavePro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblQtd, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(LblMaxNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAddPro)
                                .addComponent(btnMenosPro)
                                .addComponent(jLblQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLbCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLbDescPro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSavePro)
                            .addComponent(LblMaxNumber)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfCod, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnNew))))
                .addContainerGap(257, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCbCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbCliActionPerformed

    private void jTbProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbProMouseClicked
        // TODO add your handling code here:
        selected = jTbPro.getSelectedRow();
        
        if (selected != -1) {
            jLbCodPro.setText(jTbPro.getValueAt(selected, 0).toString());
            jLbDescPro.setText(jTbPro.getValueAt(selected, 1).toString());
            maxCount = Float.parseFloat(jTbPro.getValueAt(selected, 3).toString());
            LblMaxNumber.setText("");
        }
    }//GEN-LAST:event_jTbProMouseClicked

    private void btnAddProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProActionPerformed
        // TODO add your handling code here:
        if (count < maxCount) {
            count++;
        }
        jLblQtd.setText(String.valueOf(count));
    }//GEN-LAST:event_btnAddProActionPerformed

    private void btnMenosProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosProActionPerformed
        // TODO add your handling code here:
        if (count > 1) {
            count--;
        }
        jLblQtd.setText(String.valueOf(count));
    }//GEN-LAST:event_btnMenosProActionPerformed

    private void btnSaveProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveProActionPerformed
        // TODO add your handling code here:
        float qtd=0;
        if (Integer.parseInt(jLblQtd.getText()) > maxCount) {
            qtd = maxCount;
        }
        else{
            qtd = Integer.parseInt(jLblQtd.getText());
        }
        InfPedido infPedido = new InfPedido(qtd, Integer.parseInt(jLbCodPro.getText()));
        pedidos.add(infPedido);
        loadProSelected();
    }//GEN-LAST:event_btnSaveProActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        idCliente = getIdCli(jCbCli.getSelectedIndex());
        long millis = System.currentTimeMillis();
        Pedido pedido = new Pedido(Integer.parseInt(jTfCod.getText()), new Date(millis), pedidos, idCliente);
        pedidoDaoImpl.addPedido(pedido);
        btnSave.setEnabled(false);
        btnSavePro.setEnabled(false);
        pedidos.removeAll(pedidos);
        loadProSelected();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        jTbPro.setEnabled(true);
        btnSave.setEnabled(true);
        btnSavePro.setEnabled(true);
        jTfCod.setText(String.valueOf(pedidoDaoImpl.getNextId()));
    }//GEN-LAST:event_btnNewActionPerformed

    private void jLblQtdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLblQtdKeyReleased
        // TODO add your handling code here:
        if (Integer.parseInt(jLblQtd.getText()) > maxCount) {
            LblMaxNumber.setText("O valor máximo permitido é: " + maxCount);
        }
        else{
            LblMaxNumber.setText("");
        }
    }//GEN-LAST:event_jLblQtdKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblMaxNumber;
    private javax.swing.JButton btnAddPro;
    private javax.swing.JButton btnMenosPro;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSavePro;
    private javax.swing.JComboBox<String> jCbCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jLbCodPro;
    private javax.swing.JTextField jLbDescPro;
    private javax.swing.JTextField jLblQtd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTbPro;
    private javax.swing.JTextField jTfCod;
    // End of variables declaration//GEN-END:variables
}
