
import dao.ClienteDao;
import dao.ClienteDaoImpl;
import model.Cliente;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author bruno_busarello
 */
public class CadClient extends javax.swing.JInternalFrame {
    public static boolean editCli = false;
    
    /**
     * Creates new form CadClient
     */
    
    ClienteDaoImpl clienteDao = new ClienteDaoImpl();
    
    public void loadCli(){
        DefaultTableModel defaultCli = new DefaultTableModel(new Object[]{
            "Código",
            "Nome",
            "Fone",
            "Email",
            "Endereço"
        }, 0);
        
        
        List<Cliente> clientes = clienteDao.getAllClientes();
        for (Cliente cliente : clientes) {
            Object linha[] = new Object[] {
                cliente.getCodigo(),
                cliente.getNome(),
                cliente.getFone(),
                cliente.getEmail(),
                cliente.getEndereco(),
            };
            defaultCli.addRow(linha);
        }
        jTbCli.setModel(defaultCli);
    }
    
    // <editor-fold defaultstate="collapsed" desc="CLIENTE: FUNÇÕES ADICIONAIS">
    // Habilita ou desabilita os inputs
    public void enableCli(boolean ena){
        jTfCodCli.setEnabled(false);
        jTfEmailCli.setEnabled(ena);
        jTfNomeCli.setEnabled(ena);
        jTfPhoneCli.setEnabled(ena);
        jTaAddCli.setEnabled(ena);
    }
    
    // Desabilita todos botões e inputs
    // Habilita o botão NOVO
    public void newCli(){
        btnNewCli.setEnabled(true);
        btnSaveCli.setEnabled(false);
        btnDltCli.setEnabled(false);
        btnCnlCli.setEnabled(false);
        btnEditCli.setEnabled(false);
        enableCli(false);
        limpaCli();
    }
    
    // Reseta todos os inputs
    public void limpaCli(){
        jTaAddCli.setText("");
        jTfCodCli.setText("");
        jTfEmailCli.setText("");
        jTfNomeCli.setText("");
        jTfPhoneCli.setText("");
        
    }
    
    // Verifica se todos os inputs estão preenchidos
    public boolean verificaEdicaoCli(){
        return (!jTfCodCli.getText().isBlank() && !jTfNomeCli.getText().isBlank() &&
            !jTfPhoneCli.getText().isBlank() && !jTfEmailCli.getText().isBlank()
            && !jTaAddCli.getText().isBlank());
    }
    // </editor-fold>
    
    public CadClient() {
        initComponents();
        loadCli();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTbCli = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTfCodCli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTfNomeCli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTfPhoneCli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTfEmailCli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTaAddCli = new javax.swing.JTextArea();
        btnNewCli = new javax.swing.JButton();
        btnEditCli = new javax.swing.JButton();
        btnCnlCli = new javax.swing.JButton();
        btnSaveCli = new javax.swing.JButton();
        btnDltCli = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jTbCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matrícula", "Nome", "Fone", "Email", "Endereço"
            }
        ));
        jTbCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbCliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTbCli);

        jLabel2.setText("Matrícula");

        jTfCodCli.setEnabled(false);
        jTfCodCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfCodCliKeyReleased(evt);
            }
        });

        jLabel3.setText("Nome");

        jTfNomeCli.setEnabled(false);
        jTfNomeCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfNomeCliKeyReleased(evt);
            }
        });

        jLabel4.setText("Fone");

        jTfPhoneCli.setEnabled(false);
        jTfPhoneCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfPhoneCliKeyReleased(evt);
            }
        });

        jLabel5.setText("Email");

        jTfEmailCli.setEnabled(false);
        jTfEmailCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfEmailCliKeyReleased(evt);
            }
        });

        jLabel6.setText("Endereço");

        jTaAddCli.setColumns(20);
        jTaAddCli.setRows(5);
        jTaAddCli.setEnabled(false);
        jTaAddCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTaAddCliKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTaAddCli);

        btnNewCli.setText("Novo");
        btnNewCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCliActionPerformed(evt);
            }
        });

        btnEditCli.setText("Editar");
        btnEditCli.setEnabled(false);
        btnEditCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCliActionPerformed(evt);
            }
        });

        btnCnlCli.setText("Cancelar");
        btnCnlCli.setEnabled(false);
        btnCnlCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCnlCliActionPerformed(evt);
            }
        });

        btnSaveCli.setText("Salvar");
        btnSaveCli.setEnabled(false);
        btnSaveCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCliActionPerformed(evt);
            }
        });

        btnDltCli.setText("Excluir");
        btnDltCli.setEnabled(false);
        btnDltCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDltCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jTfCodCli)
                    .addComponent(jLabel3)
                    .addComponent(jTfNomeCli, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jTfPhoneCli, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jTfEmailCli, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnNewCli)
                .addGap(18, 18, 18)
                .addComponent(btnEditCli)
                .addGap(18, 18, 18)
                .addComponent(btnCnlCli)
                .addGap(18, 18, 18)
                .addComponent(btnDltCli)
                .addGap(18, 18, 18)
                .addComponent(btnSaveCli)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfPhoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewCli)
                    .addComponent(btnEditCli)
                    .addComponent(btnCnlCli)
                    .addComponent(btnDltCli)
                    .addComponent(btnSaveCli))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCliActionPerformed
        // TODO add your handling code here:
        editCli = true;
        btnDltCli.setEnabled(false);
        enableCli(true);
    }//GEN-LAST:event_btnEditCliActionPerformed

    private void btnCnlCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCnlCliActionPerformed
        // TODO add your handling code here:
        limpaCli();
        enableCli(false);
        btnNewCli.setEnabled(true);
        btnSaveCli.setEnabled(false);
        btnCnlCli.setEnabled(false);
        btnEditCli.setEnabled(false);
        btnDltCli.setEnabled(false);
        jTbCli.setRowSelectionAllowed(false);
    }//GEN-LAST:event_btnCnlCliActionPerformed

    private void btnSaveCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCliActionPerformed
        // TODO add your handling code here:
        int cod = Integer.parseInt(jTfCodCli.getText());
        String nome = jTfNomeCli.getText();
        String fone = jTfPhoneCli.getText();
        String email = jTfEmailCli.getText();
        String endereco = jTaAddCli.getText();
        
        int opt = JOptionPane.showConfirmDialog(null, 
                "Deseja realmente salvar essas informações?\n\n" + 
                "\nNome: " + nome +
                "\nTelefone: " + fone +
                "\nEmail: " + email +
                "\nEndereço: " + endereco,
                "Confirmar",
                JOptionPane.YES_NO_OPTION
                );
        
        if (opt == JOptionPane.YES_OPTION) {
            Cliente cliente = new Cliente(cod, nome, fone, email, endereco);
            
            enableCli(false);
            limpaCli();
            btnNewCli.setEnabled(true);
            btnSaveCli.setEnabled(false);
            btnCnlCli.setEnabled(false);
            if (editCli) {
                clienteDao.updateCliente(cliente);
                editCli = false;
            }
            else{
                clienteDao.addCliente(cliente);
            }
            newCli();
            loadCli();
        }
    }//GEN-LAST:event_btnSaveCliActionPerformed

    private void btnDltCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDltCliActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, 
                "Deseja realmente excluir este registro?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION);
        if (opt == JOptionPane.YES_OPTION) {
            clienteDao.deleteCliente(Integer.parseInt(jTfCodCli.getText()));
            loadCli();
        }
    }//GEN-LAST:event_btnDltCliActionPerformed

    private void btnNewCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCliActionPerformed
        // TODO add your handling code here:
        btnCnlCli.setEnabled(true);
        btnNewCli.setEnabled(false);
        enableCli(true);
    }//GEN-LAST:event_btnNewCliActionPerformed

    private void jTbCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbCliMouseClicked
        // TODO add your handling code here:
        int selectedCli = jTbCli.getSelectedRow();
        
        enableCli(false);
        btnNewCli.setEnabled(false);
        btnCnlCli.setEnabled(true);
        btnEditCli.setEnabled(true);
        btnDltCli.setEnabled(true);
        
        jTbCli.setRowSelectionAllowed(true);
        
        jTfCodCli.setText(jTbCli.getValueAt(selectedCli, 0).toString());
        jTfNomeCli.setText(jTbCli.getValueAt(selectedCli, 1).toString());
        jTfPhoneCli.setText(jTbCli.getValueAt(selectedCli, 2).toString());
        jTfEmailCli.setText(jTbCli.getValueAt(selectedCli, 3).toString());
        jTaAddCli.setText(jTbCli.getValueAt(selectedCli, 4).toString());
    }//GEN-LAST:event_jTbCliMouseClicked

    private void jTfCodCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfCodCliKeyReleased
        // TODO add your handling code here:
        btnSaveCli.setEnabled(verificaEdicaoCli());
    }//GEN-LAST:event_jTfCodCliKeyReleased

    private void jTfNomeCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfNomeCliKeyReleased
        // TODO add your handling code here:
        btnSaveCli.setEnabled(verificaEdicaoCli());
    }//GEN-LAST:event_jTfNomeCliKeyReleased

    private void jTfPhoneCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfPhoneCliKeyReleased
        // TODO add your handling code here:
        btnSaveCli.setEnabled(verificaEdicaoCli());
    }//GEN-LAST:event_jTfPhoneCliKeyReleased

    private void jTfEmailCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfEmailCliKeyReleased
        // TODO add your handling code here:
        btnSaveCli.setEnabled(verificaEdicaoCli());
    }//GEN-LAST:event_jTfEmailCliKeyReleased

    private void jTaAddCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTaAddCliKeyReleased
        // TODO add your handling code here:
        btnSaveCli.setEnabled(verificaEdicaoCli());
    }//GEN-LAST:event_jTaAddCliKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCnlCli;
    private javax.swing.JButton btnDltCli;
    private javax.swing.JButton btnEditCli;
    private javax.swing.JButton btnNewCli;
    private javax.swing.JButton btnSaveCli;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTaAddCli;
    private javax.swing.JTable jTbCli;
    private javax.swing.JTextField jTfCodCli;
    private javax.swing.JTextField jTfEmailCli;
    private javax.swing.JTextField jTfNomeCli;
    private javax.swing.JTextField jTfPhoneCli;
    // End of variables declaration//GEN-END:variables
}
