
import dao.ProdutoDaoImpl;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.JOptionPane;
import model.Produto;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author bruno_busarello
 */
public class CadProduto extends javax.swing.JInternalFrame {
    public static boolean editPro = false;
    
    ProdutoDaoImpl produtoDao = new ProdutoDaoImpl();
    
    public void loadPro(){
        DefaultTableModel defaultPro = new DefaultTableModel(new Object[]{
            "Código",
            "Preço",
            "Unidade",
            "Quantidade",
            "Descricao"
        }, 0);
        
        
        List<Produto> produtos = produtoDao.getAllProdutos();
        for (Produto produto : produtos) {
            Object linha[] = new Object[] {
                produto.getCod(),
                produto.getPreco(),
                produto.getUnit(),
                produto.getQtd(),
                produto.getDesc(),
            };
            defaultPro.addRow(linha);
        }
        jTbPro.setModel(defaultPro);
    }
    
    //<editor-fold defaultstate="collapsed" desc="PRODUTO: FUNÇÕES ADICIONAIS">
    public void enablePro(boolean ena){
        jTfCodPro.setEnabled(false);
        jTfPricePro.setEnabled(ena);
        jTfQtdPro.setEnabled(ena);
        jTfUnitPro.setEnabled(ena);
        jTaDescPro.setEnabled(ena);
    }
    
    public void newPro(){
        btnNewPro.setEnabled(true);
        btnSavePro.setEnabled(false);
        btnDltPro.setEnabled(false);
        btnCnlPro.setEnabled(false);
        btnEditPro.setEnabled(false);
        enablePro(false);
        limpaPro();
    }
    
    public void limpaPro(){
        jTaDescPro.setText("");
        jTfCodPro.setText("");
        jTfPricePro.setText("");
        jTfQtdPro.setText("");
        jTfUnitPro.setText("");
    }
    
    public boolean verificaEdicaoPro(){
        return (!jTfPricePro.getText().isBlank() &&
            !jTfQtdPro.getText().isBlank() && !jTfUnitPro.getText().isBlank()
            && !jTaDescPro.getText().isBlank());
    }
    //</editor-fold>
    
    /**
     * Creates new form CadProduto
     */
    public CadProduto() {
        initComponents();
        loadPro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTbPro = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTfCodPro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTfPricePro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTfUnitPro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTfQtdPro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTaDescPro = new javax.swing.JTextArea();
        btnNewPro = new javax.swing.JButton();
        btnEditPro = new javax.swing.JButton();
        btnCnlPro = new javax.swing.JButton();
        btnSavePro = new javax.swing.JButton();
        btnDltPro = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jTbPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Preço", "Unidade", "Quantidade", "Descrição"
            }
        ));
        jTbPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbProMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTbPro);

        jLabel2.setText("Código");

        jTfCodPro.setEnabled(false);
        jTfCodPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfCodProKeyReleased(evt);
            }
        });

        jLabel3.setText("Preço");

        jTfPricePro.setEnabled(false);
        jTfPricePro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfPriceProKeyReleased(evt);
            }
        });

        jLabel4.setText("Unidade");

        jTfUnitPro.setEnabled(false);
        jTfUnitPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfUnitProKeyReleased(evt);
            }
        });

        jLabel5.setText("Quantidade");

        jTfQtdPro.setEnabled(false);
        jTfQtdPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfQtdProKeyReleased(evt);
            }
        });

        jLabel6.setText("Descrição");

        jTaDescPro.setColumns(20);
        jTaDescPro.setRows(5);
        jTaDescPro.setEnabled(false);
        jTaDescPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTaDescProKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTaDescPro);

        btnNewPro.setText("Novo");
        btnNewPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProActionPerformed(evt);
            }
        });

        btnEditPro.setText("Editar");
        btnEditPro.setEnabled(false);
        btnEditPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProActionPerformed(evt);
            }
        });

        btnCnlPro.setText("Cancelar");
        btnCnlPro.setEnabled(false);
        btnCnlPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCnlProActionPerformed(evt);
            }
        });

        btnSavePro.setText("Salvar");
        btnSavePro.setEnabled(false);
        btnSavePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveProActionPerformed(evt);
            }
        });

        btnDltPro.setText("Excluir");
        btnDltPro.setEnabled(false);
        btnDltPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDltProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jTfCodPro)
                    .addComponent(jLabel3)
                    .addComponent(jTfPricePro, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jTfUnitPro, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jTfQtdPro, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnNewPro)
                .addGap(18, 18, 18)
                .addComponent(btnEditPro)
                .addGap(18, 18, 18)
                .addComponent(btnCnlPro)
                .addGap(18, 18, 18)
                .addComponent(btnDltPro)
                .addGap(18, 18, 18)
                .addComponent(btnSavePro)
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfPricePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfUnitPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfQtdPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewPro)
                    .addComponent(btnEditPro)
                    .addComponent(btnCnlPro)
                    .addComponent(btnDltPro)
                    .addComponent(btnSavePro))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProActionPerformed
        // TODO add your handling code here:
        editPro = true;
        btnDltPro.setEnabled(false);
        enablePro(true);
    }//GEN-LAST:event_btnEditProActionPerformed

    private void btnCnlProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCnlProActionPerformed
        // TODO add your handling code here:
        limpaPro();
        enablePro(false);
        btnNewPro.setEnabled(true);
        btnSavePro.setEnabled(false);
        btnCnlPro.setEnabled(false);
        btnEditPro.setEnabled(false);
        btnDltPro.setEnabled(false);
        jTbPro.setRowSelectionAllowed(false);
    }//GEN-LAST:event_btnCnlProActionPerformed

    private void btnSaveProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveProActionPerformed
        // TODO add your handling code here:
        int cod = Integer.parseInt(jTfCodPro.getText());
        String unidade = jTfUnitPro.getText();
        float preco = Float.parseFloat(jTfPricePro.getText());
        float qtd = Float.parseFloat(jTfQtdPro.getText());
        String desc = jTaDescPro.getText();
        
        int opt = JOptionPane.showConfirmDialog(null, 
                "Deseja realmente salvar essas informações?\n\n" + 
                "Código: " + cod +
                "\nUnidade: " + unidade +
                "\nPreço: " + preco +
                "\nQuantidade: " + qtd +
                "\nDescrição: " + desc,
                "Confirmar",
                JOptionPane.YES_NO_OPTION
                );
        
        if (opt == JOptionPane.YES_OPTION) {
            Produto produto = new Produto(cod, desc, unidade, qtd, preco);
            
            if (editPro) {
                produtoDao.updateProduto(produto);
                editPro = false;
            }
            else{
                produtoDao.addProduto(produto);
            }
            newPro();
            loadPro();
        }
    }//GEN-LAST:event_btnSaveProActionPerformed

    private void btnDltProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDltProActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, 
                "Deseja realmente excluir este registro?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION);
        if (opt == JOptionPane.YES_OPTION) {
            produtoDao.deleteProduto(Integer.parseInt(jTfCodPro.getText()));
            loadPro();
            newPro();
        }
    }//GEN-LAST:event_btnDltProActionPerformed

    private void btnNewProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProActionPerformed
        // TODO add your handling code here:
        btnCnlPro.setEnabled(true);
        btnNewPro.setEnabled(false);
        enablePro(true);
    }//GEN-LAST:event_btnNewProActionPerformed

    private void jTbProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbProMouseClicked
        // TODO add your handling code here:
        int selectedPro = jTbPro.getSelectedRow();
        
        enablePro(false);
        btnNewPro.setEnabled(false);
        btnCnlPro.setEnabled(true);
        btnEditPro.setEnabled(true);
        btnDltPro.setEnabled(true);
        
        jTbPro.setRowSelectionAllowed(true);
        
        jTfCodPro.setText(jTbPro.getValueAt(selectedPro, 0).toString());
        jTfPricePro.setText(jTbPro.getValueAt(selectedPro, 1).toString());
        jTfQtdPro.setText(jTbPro.getValueAt(selectedPro, 2).toString());
        jTfUnitPro.setText(jTbPro.getValueAt(selectedPro, 3).toString());
        jTaDescPro.setText(jTbPro.getValueAt(selectedPro, 4).toString());
    }//GEN-LAST:event_jTbProMouseClicked

    private void jTfCodProKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfCodProKeyReleased
        // TODO add your handling code here:
        btnSavePro.setEnabled(verificaEdicaoPro());
    }//GEN-LAST:event_jTfCodProKeyReleased

    private void jTfPriceProKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfPriceProKeyReleased
        // TODO add your handling code here:
        btnSavePro.setEnabled(verificaEdicaoPro());
    }//GEN-LAST:event_jTfPriceProKeyReleased

    private void jTfUnitProKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfUnitProKeyReleased
        // TODO add your handling code here:
        btnSavePro.setEnabled(verificaEdicaoPro());
    }//GEN-LAST:event_jTfUnitProKeyReleased

    private void jTfQtdProKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfQtdProKeyReleased
        // TODO add your handling code here:
        btnSavePro.setEnabled(verificaEdicaoPro());
    }//GEN-LAST:event_jTfQtdProKeyReleased

    private void jTaDescProKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTaDescProKeyReleased
        // TODO add your handling code here:
        btnSavePro.setEnabled(verificaEdicaoPro());
    }//GEN-LAST:event_jTaDescProKeyReleased

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCnlPro;
    private javax.swing.JButton btnDltPro;
    private javax.swing.JButton btnEditPro;
    private javax.swing.JButton btnNewPro;
    private javax.swing.JButton btnSavePro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTaDescPro;
    private javax.swing.JTable jTbPro;
    private javax.swing.JTextField jTfCodPro;
    private javax.swing.JTextField jTfPricePro;
    private javax.swing.JTextField jTfQtdPro;
    private javax.swing.JTextField jTfUnitPro;
    // End of variables declaration//GEN-END:variables
}
